#!/bin/bash

eval $(maws li general-services)
alias t=terraform
cd infrastructure
terraform fmt
terraform validate
CLUSTER_NAME=btsec-pov-$(date +%s | base64 | cut -c10-15)
terraform apply -auto-approve -var cluster_name=$CLUSTER_NAME
