---
- hosts: nodes
  gather_facts: no
  become: yes
  tasks: 
  
  - name: Set SELinux
    become: true
    shell: setenforce 0
  
  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled

  - name: Ensure sysctl net.ipv4.ip_forward is set to 0
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present
      reload: yes
  
  - name: Set local persistent storage
    ansible.builtin.script:
      cmd: local_storage.sh

  - name: Copy over the cluster-pp script
    ansible.builtin.copy:
      src: cluster-pp.sh
      dest: /tmp/cluster-pp.sh
      owner: centos
      group: centos
      mode: '0764'

  - name: Copy over the cluster definition
    ansible.builtin.copy:
      src: cluster-sbx.yaml
      dest: /tmp/cluster-sbx.yaml
      owner: centos
      group: centos
      mode: '0664'

  - name: Copy over the metallb config
    ansible.builtin.copy:
      src: mlb.yaml
      dest: /tmp/mlb.yaml
      owner: centos
      group: centos
      mode: '0664'

- hosts: local
  gather_facts: no
  become: yes
  tasks: 
  
  - name: adding centos user to the docker group
    user:
      name: centos
      groups: docker
      append: yes
    