---
- hosts: all
  gather_facts: no
  become: yes
  tasks: 
  
  - name: Set SELinux
    become: true
    shell: setenforce 0
  
  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled

  - name: Ensure sysctl net.ipv4.ip_forward is set to 0
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present
      reload: yes
  
  - name: Set local persistent storage
    ansible.builtin.script:
      cmd: local_storage.sh